### ISSUE TITLE
Button disappeared from Asana

### ISSUE THREAD

**Issue by kleinpetr** [toggl/toggl-button#1359]
* **Ubuntu 18.04 | Chrome OS (pixelbook)**: 
* **72.0.3626.121 | 72.0.3626.122**: 
* **1.23.4**: .

#### Relevant integration (if any):
https://app.asana.com

### 🐛 Describe the bug
The button is showed for months correctly. Before week I installed extension to pixelbook with ChromeOS and button was hiding in asana, today button disappeared in Ubuntu too.

### Expected behaviour
Button disappeared.

### Steps to reproduce

Steps to reproduce the behaviour:

**Comment by fievelk** [comment]
Same issue on Trello.

**Comment by TIIUNDER** [comment]
Same for Meistertask and Todoist. Is there some setting which has to be updated?

**Comment by itsxtema** [comment]
Same for Todoist and all Google apps

**Comment by teusch** [comment]
Same issue in freshdesk (and in trello in chrome and firefox)

**Comment by fievelk** [comment]
This is the general issue: #1360.

**Comment by tcrammond** [comment]
Thank you for all the reports and your patience. Version `1.24.1` should fix most problems, it should arrive in your browsers soon.

@kleinpetr Please let us know if you still have problems with Asana (specifically) on the new version.

**Comment by kleinpetr** [comment]
Thanks. On my Ubuntu 18.04 now working fine again. But on my Pixelbook still not working. I am added screenshot from Asana. 
![Screenshot 2019-03-25 at 17 30 22](https://user-images.githubusercontent.com/17269309/54937051-01418980-4f24-11e9-87d8-2ee98786b45a.png)

**Comment by iosifnicolae2** [comment]
Same for Github.

**Comment by shantanuraj** [comment]
@iosifnicolae2 yeah version 1.24.0 had the problem.

It was fixed in version 1.24.1, which has been deployed yesterday.
If you haven't got it automatically now, could you try and manually update the extension from the `chrome://extensions` page

**Comment by iosifnicolae2** [comment]
I reinstalled the extension and now it works.
Thanks @shantanuraj .

**Comment by kleinpetr** [comment]
I reinstalled and on Ubuntu it works but Chrome OS still not. Did you try it on Chrome OS?

**Comment by shantanuraj** [comment]
@kleinpetr setting up a ChromeOS emulator to test it out, in the meanwhile can you can report the extension version on your ChromeOS device `chrome://extensions`

**Comment by kleinpetr** [comment]
Yes I have the newest version 
![Screenshot 2019-03-26 at 10 07 20](https://user-images.githubusercontent.com/17269309/54984448-2d561c80-4faf-11e9-9b84-7d44fb9adb08.png)

**Comment by shantanuraj** [comment]
@kleinpetr it seems to be working fine on my ChromeOS instance 

![image](https://user-images.githubusercontent.com/1716853/54986585-ef6dee00-4fd8-11e9-92be-c7da79fc0605.png)

Can you confirm if you have the integration enabled in the extension options

![image](https://user-images.githubusercontent.com/1716853/54986645-08769f00-4fd9-11e9-9e34-6f3c358aa75e.png)

**Comment by shantanuraj** [comment]
@kleinpetr is it still broken for you with the integration enabled in the settings?

**Comment by kleinpetr** [comment]
@shantanuraj now its working fine. Thank you!
