### ISSUE TITLE
Labels and Tags

### ISSUE THREAD

**Issue by einarsvan** [toggl/toggl-button#137]
Hi guys

This is a feature request regarding labels (Trello) and tags (Toggl). 
It would be awesome if the timer extension could take the selected labels from Trello and create/apply them as tags in Toggl.

The drop down you get when starting the timer inside Trello would present you with a description field and a project selector as usual, but also a list of the tags selected.

A more advanced solution could syncronize the tags and labels together, but to start with this would not be necessary.

**Comment by yaelruhrberg** [comment]
Hi,

I see that this issue is resolved in 2014 but I can't see this is actually working. Am I missing something?

**Comment by federinik** [comment]
I agree with @yaelruhrberg in saying that would be a nice feature and seems it's still not available
