### ISSUE TITLE
Keyboard unable to be used to choose project/tag while added task

### ISSUE THREAD

**Issue by dianetoggl** [toggl/toggl-button#1523]
Chrome/Firefox

### 🐛 Describe the bug

Users can't use the keyboard to select projects or tags while adding a task. Tab focuses on the project field or the tag field, but you are unable to open either option and choose a project/tag. 

### Expected behaviour

User can tab to project / tag field and press enter or down key to choose a project / tag.

### Steps to reproduce

- Click the Toggl Button in the menu bar.
- Click the task description field  and fill a description.
- Press tab to focus the project dropdown field.
- The project dropdown is now focused (indicated by a dotted border) but there's no way  to open it.
- Same thing if you tab down to the Tags dropdown.

### Other details or context

Support have tested in Chrome and Firefox and are able to reproduce every time.

**Comment by dianetoggl** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3540765/conversations/24151686987)

**Comment by lise-toggl** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/21681804387)

**Comment by tcrammond** [comment]
Directly related to #1511, should get fixed by it when it's merged.

**Comment by dianetoggl** [comment]
@tcrammond I noticed the PR has merged, but the issue is still persisting in the button as far as I can tell :)

**Comment by tcrammond** [comment]
Should now be resolved in version `1.46.4` 🚀
