### ISSUE TITLE
Clicking on the "Start Timer" button in Trello doesn't use my default project settings.

### ISSUE THREAD

**Issue by emilecantin** [toggl/toggl-button#608]
I have to add it manually each time, it's very annoying.

**Comment by IndrekV** [comment]
I'm not able to reproduce this right now. We have made some improvements to default project handling so this issue is probably fixed in next release (planned for this week).

**Comment by emilecantin** [comment]
It's still not fixed. I had a look through the code, and it looks like it tries to guess the project from the board name. The names don't match in my case, so it doesn't fill in the project. I believe it should use the default project in that case.

**Comment by IndrekV** [comment]
Thank you for getting back to me I'll do some more test to replicate.

**Comment by IndrekV** [comment]
I'm still not able to reproduce this. I would suggest trying to re-install the extension and resetting the default project.

**Comment by emilecantin** [comment]
I reinstalled the extension, as you said, but the issue is still present. I stepped through the code when adding a time entry, and found the issue:

https://github.com/toggl/toggl-button/blob/master/src/scripts/background.js#L410

The code around that line looks like this:

```javascript
    // set Default project if needed
    if (!entry.time_entry.pid && !!defaultProject) {
      project = TogglButton.findProjectByPid(parseInt(defaultProject, 10));
      entry.time_entry.pid = project && project.pid;
      entry.time_entry.billable = project && project.billable;
    }
```

The issue is that `project.pid` is undefined. It has a `id`, a `cid`, and a `wid`, though. `defaultProject` is a string containing the same number as `project.id`. Should we use `project.id`  instead of `project.pid`?

 Here is the output of `JSON.stringify(project)` at that point:

```json
"{"id":11548495,"wid":1124304,"cid":17594812,"name":"Operations: Alpha Release","billable":false,"is_private":false,"active":true,"template":false,"at":"2016-08-18T18:25:56+00:00","created_at":"2015-10-02T20:07:17+00:00","color":"3","auto_estimates":false,"actual_hours":5951,"hex_color":"#f68d38"}"
```

**Comment by IndrekV** [comment]
You are correct. `id` should be used instead of `pid`. Thank you for pointing that out.
